#!/bin/bash

set -e

die () {
    echo $@ >&2
    exit 1
}

# Note that the exit in END is what determines the final exit status,
# even t/pre~hough the previous exit initiates the exit.
client_winid=$(wmctrl -a :ACTIVE: -v 2>&1 \
	| awk '/^Using window:/ { print $3; exit_status = 0; exit }')

# Switch to emacs and wait for editing to be completed.
wmctrl -xa emacs || die "No emacs running"
emacsclient "$@"

# Switch back to window from which emacsclient was invoked.
wmctrl -ia $client_winid
