#!/bin/bash

set -e

# Note that the exit in END is what determines the final exit status, even
# though the previous exit initiates the exit.
client_winid=$(wmctrl -a :ACTIVE: -v 2>&1 \
	| awk '/^Using window:/ { print $3; exit_status = 0; exit }')

# Switch to emacs and wait for editing to complete.
if ! wmctrl -xa emacs ; then
    emacs -nw $@;
elif ! [ $# = 0 ] ; then
    emacsclient $@ || true

    # Switch back to window from which emacsclient was invoked.
    wmctrl -ia $client_winid
else
    # Nothing, just switch to emacs
    echo "Showing emacs window." >&2
fi
